import { Recipe } from '../helpers/types';

export const recipes: Recipe[] = [
  {
    id: '158961',
    slug: '158961-easy-indian-chicken-curry-with-minted-masala-rice',
    title: 'Easy Indian Chicken Curry',
    subtitle: 'with Minted Masala Rice',
    mealType: 'MEAT',
    recipeType: 'PREMIUM',
    category: { displayText: 'Meat', __typename: 'MealCategory' },
    image: {
      url: 'https://marleyspoon.com/media/recipes/158961/main_photos/medium/easy-cde135e964e1ba41257767eea724ec18.jpeg',
      __typename: 'Image',
    },
    attributes: [
      { key: 'no_gluten_ingredients', __typename: 'MealAttribute' },
      { key: 'under_30min', __typename: 'MealAttribute' },
      { key: 'poultry', __typename: 'MealAttribute' },
      { key: 'kid_friendly', __typename: 'MealAttribute' },
      { key: 'dairy_free', __typename: 'MealAttribute' },
    ],
    extraFees: [],
    __typename: 'Recipe',
  },
  {
    id: '146620',
    slug: '146620-smoky-barbecue-pork-meatballs-with-veggie-loaded-mash',
    title: 'Smoky Barbecue Pork Meatballs',
    subtitle: 'with Veggie-Loaded Mash',
    mealType: 'MEAT',
    recipeType: 'PREMIUM',
    category: { displayText: 'Meat', __typename: 'MealCategory' },
    image: {
      url: 'https://marleyspoon.com/media/recipes/146620/main_photos/medium/smoky_barbecue_pork_meatballs-ae89fd911c5ed391ede5442bf05c210e.jpeg',
      __typename: 'Image',
    },
    attributes: [
      { key: 'no_gluten_ingredients', __typename: 'MealAttribute' },
      { key: 'meat', __typename: 'MealAttribute' },
      { key: 'kid_friendly', __typename: 'MealAttribute' },
    ],
    extraFees: [],
    __typename: 'Recipe',
  },
  {
    id: '158967',
    slug: '158967-kid-approved-asian-twist-beef-bolognese-with-spaghetti-and-spring-onion',
    title: 'Asian Twist Beef Bolognese',
    subtitle: 'with Spaghetti and Spring Onion',
    mealType: 'MEAT',
    recipeType: 'STANDARD',
    category: { displayText: 'Meat', __typename: 'MealCategory' },
    image: {
      url: 'https://marleyspoon.com/media/recipes/158967/main_photos/medium/kid_approved_asian_twist_beef_bolognese-a9c9c28f3bd56290aabd36c3fd910f05.jpeg',
      __typename: 'Image',
    },
    attributes: [
      { key: 'under_30min', __typename: 'MealAttribute' },
      { key: 'meat', __typename: 'MealAttribute' },
      { key: 'kid_friendly', __typename: 'MealAttribute' },
      { key: 'dairy_free', __typename: 'MealAttribute' },
    ],
    extraFees: [],
    __typename: 'Recipe',
  },
  {
    id: '131995',
    slug: '131995-loaded-golden-chicken-bowl-with-spiced-potatoes-and-tomato',
    title: 'Loaded Golden Chicken Bowl',
    subtitle: 'with Spiced Potatoes and Tomato',
    mealType: 'MEAT',
    recipeType: 'STANDARD',
    category: { displayText: 'Meat', __typename: 'MealCategory' },
    image: {
      url: 'https://marleyspoon.com/media/recipes/131995/main_photos/medium/loaded_golden_chicken_bowl-a6c007c210929bd30c689414ff05e773.jpeg',
      __typename: 'Image',
    },
    attributes: [
      { key: 'no_gluten_ingredients', __typename: 'MealAttribute' },
      { key: 'poultry', __typename: 'MealAttribute' },
      { key: 'kid_friendly', __typename: 'MealAttribute' },
      { key: 'dairy_free', __typename: 'MealAttribute' },
      { key: 'optional_heat', __typename: 'MealAttribute' },
    ],
    extraFees: [],
    __typename: 'Recipe',
  },
  {
    id: '158188',
    slug: '158188-comfort-food-tropical-bacon-tacos-with-roast-potato-and-pineapple-salsa',
    title: 'Tropical Bacon Tacos',
    subtitle: 'with Roast Potato and Pineapple Salsa',
    mealType: 'MEAT',
    recipeType: 'STANDARD',
    category: { displayText: 'Meat', __typename: 'MealCategory' },
    image: {
      url: 'https://marleyspoon.com/media/recipes/158188/main_photos/medium/comfort-db28224c53003dd8736030fae26273d7.jpeg',
      __typename: 'Image',
    },
    attributes: [
      { key: 'meat', __typename: 'MealAttribute' },
      { key: 'kid_friendly', __typename: 'MealAttribute' },
      { key: 'dairy_free', __typename: 'MealAttribute' },
    ],
    extraFees: [],
    __typename: 'Recipe',
  },
  {
    id: '158190',
    slug: '158190-comfort-food-sticky-thai-chicken-wings-with-sweet-potato-gems-and-rice',
    title: 'Sticky Thai Chicken Wings',
    subtitle: 'with Sweet Potato Gems and Rice',
    mealType: 'MEAT',
    recipeType: 'STANDARD',
    category: { displayText: 'Meat', __typename: 'MealCategory' },
    image: {
      url: 'https://marleyspoon.com/media/recipes/158190/main_photos/medium/comfort-044756b8018dcbc81bf103d11ad817a9.jpeg',
      __typename: 'Image',
    },
    attributes: [
      { key: 'no_gluten_ingredients', __typename: 'MealAttribute' },
      { key: 'poultry', __typename: 'MealAttribute' },
      { key: 'kid_friendly', __typename: 'MealAttribute' },
      { key: 'dairy_free', __typename: 'MealAttribute' },
    ],
    extraFees: [],
    __typename: 'Recipe',
  },
  {
    id: '126978',
    slug: '126978-haloumi-and-roast-veggie-pasta-with-toasted-almonds-and-rocket',
    title: 'Haloumi and Roast Veggie Pasta',
    subtitle: 'with Toasted Almonds and Rocket',
    mealType: 'VEGGIE',
    recipeType: 'STANDARD',
    category: { displayText: 'Veggie', __typename: 'MealCategory' },
    image: {
      url: 'https://marleyspoon.com/media/recipes/126978/main_photos/medium/roasted_capsicum_and_tomato_haloumi_pasta-33aadafe1d50494521d1629e260f377a.jpeg',
      __typename: 'Image',
    },
    attributes: [
      { key: 'vegetarian', __typename: 'MealAttribute' },
      { key: 'kid_friendly', __typename: 'MealAttribute' },
    ],
    extraFees: [],
    __typename: 'Recipe',
  },
  {
    id: '157883',
    slug: '157883-festive-main-cranberry-chutney-chicken-with-hasselback-sweet-potatoes',
    title: 'Cranberry Chutney Chicken',
    subtitle: 'with Hasselback Sweet Potatoes',
    mealType: 'MEAT',
    recipeType: 'STANDARD',
    category: { displayText: 'Meat', __typename: 'MealCategory' },
    image: {
      url: 'https://marleyspoon.com/media/recipes/157883/main_photos/medium/all-15deea539a07c393c3e8d38e27e7252a.jpeg',
      __typename: 'Image',
    },
    attributes: [
      { key: 'no_gluten_ingredients', __typename: 'MealAttribute' },
      { key: 'poultry', __typename: 'MealAttribute' },
      { key: 'kid_friendly', __typename: 'MealAttribute' },
      { key: 'dairy_free', __typename: 'MealAttribute' },
    ],
    extraFees: [],
    __typename: 'Recipe',
  },
];
